name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install C unit test
      run: sudo apt install libcunit1 libcunit1-dev libcunit1-doc
    - name: make run_tests_with_coverage
      run: make run_tests_with_coverage